#!/bin/bash
# This script contacts github and merges 
# repo this script is ran to update local
# repo dir files before editing local files.

# this command changes the directory to the local repo directory
cd /$HOME/Github/repo/dir &&

# pull any changes you made online
git pull &&

echo "Successful Merge $USER. Now working on ${PWD##*/}"

